const assert=require('assert/strict'),vm=require('vm'),fs=require('fs'),path=require('path');
const {ready,load,constant,table,machine,cargo,source}=require('./tests.cjs');
let count=0;function test(name,f){f();count++;console.log('PASS',name);}
function setup(mi=4){
 const c=ready();Object.assign(c,{money:100000,NIVEAUX:Array.from({length:20},(_,i)=>({nom:'Palier '+i})),GENRE_SITE:{},SILO:{x:0,z:0},ENTREPOT:{quai:{x:1,z:1}},cur:0,bravoPages:[],bravoI:0,
  peindreBravo:()=>{},titreMission:m=>m.titre||m.lieu,majBulles:()=>{},caleEspece:()=>{},champEtape:(e,k)=>typeof e[k]==='function'?e[k]():e[k],
  TUTO:[],outilVerrou:k=>!!c.TOOLS.find(t=>t.key===k)?.verrou,cuveDe:()=>1,
  prixPature:k=>c.ESPECES[k].pature,peutAcheterParcelle:()=>true,halleLotMax:()=>17,coutUp:()=>900,
  niveauMateriel:()=>1,prixCranSuivant:()=>1200,leconCourante:()=>c.conseilProgression(),
  scene:{remove:()=>{}},missionCourante:()=>c.MISSIONS[c.CAMPAGNE.mission]||null,
  leconFaite:()=>false,vignetteDe:k=>c.VIGNETTES[k]?'produits/'+c.VIGNETTES[k]+'.png':null,
 });
 vm.runInContext(table('ATELIER_MODULES','\n];'),c);c.moduleDe=k=>c.ATELIER_MODULES.find(m=>m.cle===k);
 c.HALLE.capa=1;c.HALLE.quai={x:4,z:5};c.CAMPAGNE.mission=mi;c.CAMPAGNE.prise=true;c.CAMPAGNE.tuto=0;c.CAMPAGNE.retard=0;
 c.CAMPAGNE.lecons=[];c.CAMPAGNE.clientsPresentes=[];c.STAT.porcs=0;
 c.MACHINES=['t4','fourgon','enjambeuse','abatteuse','porteur','barque','chalutier','caseyeur','frigo','semi'].map((key,i)=>({key,nom:key,prix:[6000,9000,15000,14000,9500,3000,18000,11000,12000,26000][i],verrou:true,bateau:['barque','chalutier','caseyeur'].includes(key),v:{}}));
 c.TOOLS=[{key:'combine',nom:'Combiné',prix:15000,verrou:true},{key:'engrais',prix:250,verrou:true},{key:'grumier',prix:10000,verrou:true}];
 c.CROPS=['ble','mais','orge','avoine','colza','olives','raisin'].map(cle=>({cle,nom:cle,cout:600,verrou:cle!=='ble'}));
 c.PARCELS=[{owned:true,price:0,x:0,z:0},{owned:false,price:500,signPos:{},x:5,z:5}];
 c.ESPECES={poule:{pature:800,prix:30,pluriel:'Poules'},vache:{pature:3500,prix:600,pluriel:'Vaches'},mouton:{pature:3000,prix:180,pluriel:'Moutons'},ruche:{pature:1200,prix:250,pluriel:'Ruches'},cochon:{pature:2800,prix:220,pluriel:'Porcs'}};
 vm.runInContext(table('ACHATS_MISSIONS','\n];'),c);vm.runInContext(constant('ELEVAGES_MISSIONS'),c);
 vm.runInContext(constant('accepteNature'),c);vm.runInContext(constant('peutCharger'),c);
 vm.runInContext(table('VIGNETTES','\n};'),c);
 load(c,['achatMission','coutMissionRestant','margeProgression','conseilProgression','missionVisible','missionAPrendre','missionEnContrat','listeEtapes','etapeTuto','annoncerNiveau','pageDeblocage','ouvrirBravo','lieuLecon','lieuTuto','objectifMission','appelMenu','chargerBetail']);
 return c;
}
test('Every campaign mission waits for its client call, including preparation missions',()=>{const c=setup();for(let i=0;i<c.MISSIONS.length;i++){c.CAMPAGNE.mission=i;c.CAMPAGNE.prise=false;assert.equal(c.missionVisible(),null);assert.equal(c.missionAPrendre(),c.MISSIONS[i]);assert.equal(c.conseilProgression(),null);c.CAMPAGNE.prise=true;assert.equal(c.missionVisible(),c.MISSIONS[i]);}});
test('Baker and fertilizer preparation start only after acceptance, with the matching menu target',()=>{for(const [mi,fen,art] of [[2,'achat','engrais'],[4,'production','farine']]){const c=setup(mi);c.CAMPAGNE.prise=false;assert.equal(c.etapeTuto(),null);c.CAMPAGNE.prise=true;assert(c.etapeTuto());assert.equal(c.appelMenu().fen,fen);assert.equal(c.appelMenu().art,art);}});
test('Insufficient tutorial funds point to funding instead of highlighting an unaffordable purchase',()=>{for(const mi of [2,4]){const c=setup(mi);c.money=0;const e=c.etapeTuto();assert.equal(c.champEtape(e,'ou'),'Coopérative');assert.equal(c.appelMenu(),null);assert(c.champEtape(e,'txt').includes('FINANCER'));}});
test('A level gain never queues a shop announcement before its first delivery',()=>{const c=setup();for(let i=1;i<=20;i++)c.annoncerNiveau(i,i-1);assert.equal(c.SITES_ANNONCE.length,0);assert.equal(c.bravoPages.length,0);});
test('The first flour tutorial has a real objective at the farm workshop',()=>{const c=setup(4);const o=c.objectifMission();assert.equal(o.lieu,'atelier');assert.equal(o.x,c.HALLE.quai.x);assert.equal(o.z,c.HALLE.quai.z);});
test('Preparation phone calls have a client and valid empty merchandise rows',()=>{const c=setup();for(const mi of [11,28,32]){const m=c.MISSIONS[mi];assert.equal(m.qui,m.lieu);const offer=c.missionEnContrat(m);assert.equal(offer.lignes.length,0);assert(offer.lieu);assert(m.titre);}});
test('Required equipment uses actual prices and switches immediately from funding to purchase',()=>{const c=setup(30);c.money=13999;let l=c.conseilProgression();assert.equal(l.ou,'Coopérative');assert(l.obligatoire);c.money=14000;l=c.conseilProgression();assert.equal(l.art,'abatteuse');assert.equal(l.ou,'Garage');c.MACHINES.find(m=>m.key==='abatteuse').verrou=false;assert.equal(c.conseilProgression().art,'porteur');});
test('Fishing purchases teach distinct boats followed by refrigerated road transport',()=>{const c=setup(32);for(const [key,where] of [['barque','Comptoir des pêcheurs'],['caseyeur','Comptoir des pêcheurs'],['frigo','Garage']]){assert.equal(c.conseilProgression().art,key);assert.equal(c.conseilProgression().ou,where);c.MACHINES.find(m=>m.key===key).verrou=false;}});
test('An owned trawler avoids an unnecessary fishing-boat purchase',()=>{const c=setup(32);c.MACHINES.find(m=>m.key==='chalutier').verrou=false;assert.equal(c.conseilProgression().art,'caseyeur');});
test('Livestock progression preserves a crop field and guides to the cheapest available land',()=>{const c=setup(6);c.money=500;let l=c.conseilProgression();assert.equal(l.ou,'parcelle');assert.equal(c.lieuLecon(l).x,5);c.PARCELS[1].owned=true;c.money=890;l=c.conseilProgression();assert.equal(l.ou,'champ');c.PATURES=[{espece:'poule',betes:[],quai:{x:2,z:3}}];assert.equal(c.conseilProgression().ou,'pature0');});
test('A pig already delivered or aboard is not bought a second time',()=>{const c=setup(28);const m=c.MACHINES.find(m=>m.key==='fourgon');m.verrou=false;m.v.betail=2;m.v.betailEspece='cochon';c.STAT.porcs=2;c.PATURES=[{espece:'cochon',betes:[],quai:{x:2,z:3}}];const l=c.conseilProgression();assert(!l||!l.cle.startsWith('animaux-'));});
test('Comfort advice reserves required purchases for the next two calls',()=>{const c=setup(21);c.HALLE.modules=['farine'];for(const m of c.MACHINES)if(m.key==='fourgon')m.verrou=false;const reserve=c.margeProgression();assert.equal(reserve,150+600+18000);c.money=21000+reserve-1;assert.notEqual(c.conseilProgression()?.art,'t4');c.money++;assert.equal(c.conseilProgression().art,'t4');c.MACHINES.find(m=>m.key==='t4').verrou=false;c.money-=6000;assert.equal(c.conseilProgression().art,'combine');assert(c.conseilProgression().txt.includes('tracteur lourd'));});
test('Increasing a required price also increases the protected budget',()=>{const c=setup(21),n=c.margeProgression();c.moduleDe('huile').prix+=5000;assert.equal(c.margeProgression(),n+5000);});
test('No heavy-tractor comfort advice is given during early missions',()=>{const c=setup(9);c.money=999999;assert.notEqual(c.conseilProgression()?.art,'t4');assert.notEqual(c.conseilProgression()?.art,'combine');});
test('Mandatory objective and menu guidance point to the same required machine',()=>{const c=setup(30);c.money=14000;const o=c.objectifMission();assert.equal(o.lieu,'Garage');assert.equal(c.appelMenu().art,'abatteuse');});
test('All buyers show their full product catalogue after their first mission, once only',()=>{const c=setup();for(const m of c.MISSIONS){const key=m.lieu||m.qui,s=c.SITES.find(s=>s.nom===key);if(!s)continue;c.ouvrirBravo(m,null,20);const pages=c.bravoPages.filter(p=>p.titre===key.toUpperCase());if(pages.length){for(const k of new Set([...s.achete,...s.accepte]))if(!c.PRODUITS[k].interne||c.PRODUITS[k].betail)assert(pages[0].plus.includes(k),key+':'+k);}c.bravoPages=[];c.ouvrirBravo({...m,apres:[]},null,20);assert(!c.bravoPages.some(p=>p.titre===key.toUpperCase()));}assert(c.CAMPAGNE.clientsPresentes.includes('Conserverie'));});
test('Animal catalogues include animals despite their special non-cargo product type',()=>{const c=setup();const p=c.pageDeblocage(c.SITES.find(s=>s.nom==='Boucherie'));assert(p.plus.includes('betail_cochon'));assert(p.sous.includes('fourgon'));});
test('Pickup, ordinary van and grain trailer refuse both fresh sea products',()=>{const c=setup();for(const t of [{},{refuse:['grumes']},{prend:['ble','poisson']}])for(const key of ['poisson','crustaces'])assert(!c.accepteNature(t,key));});
test('Refrigerated road cargo and fishing holds keep their exact product roles',()=>{const c=setup();for(const k of ['poisson','crustaces'])assert(c.accepteNature({frigorifique:true},k));assert(c.accepteNature({calePeche:true,prend:['poisson']},'poisson'));assert(!c.accepteNature({calePeche:true,prend:['poisson']},'crustaces'));assert(!c.accepteNature({prend:['grumes']},'ble'));assert(!c.accepteNature({},'betail_cochon'));});
test('Animals use the van only, cannot mix with goods, and loading caps at five',()=>{const c=setup(),p={espece:'cochon',betes:Array.from({length:9},()=>({age:1,g:{}}))};const pickup=machine('pickup',cargo()),van=machine('fourgon',cargo());c.MACHINES=[pickup,van];c.ESPECES.cochon.cle='cochon';assert.equal(c.chargerBetail(p,pickup.v,3),0);van.v.cargo.load=1;assert.equal(c.chargerBetail(p,van.v,3),0);van.v.cargo.load=0;assert.equal(c.chargerBetail(p,van.v,9),5);assert.equal(p.betes.length,4);assert.equal(c.chargerBetail(p,van.v,1),0);assert(!c.peutCharger({load:0,capacite:100,betail:5},'ble'));});
test('Manual and stale automatic loading actions reject fresh fish in an ordinary van',()=>{const c=setup(),m=machine('fourgon',cargo());const a={sens:'pecheQuai',cle:'poisson'};assert.equal(c.quantiteMax(m,a),0);c.executer(m,a,1);assert.equal(m.v.cargo.load,0);});
test('Legacy incompatible goods can unload without permitting new loading',()=>{const c=setup();c.MODE_LIBRE=true;const s=c.SITES.find(s=>s.nom==='Poissonnerie'),m=machine('pickup',cargo(null,{poisson:10}));assert(!c.accepteNature(m.v.cargo,'poisson'));c.executer(m,{sens:'vendre',S:s,cle:'poisson'},1);assert.equal(m.v.cargo.load,0);});
test('Old preparation progress and already introduced customers survive save migration',()=>{const c=setup();c.chargerCampagne({campagne:{mv:3,tv:4,xp:1000,niveau:8,mission:11,prise:false,faits:[],tuto:99}});assert(c.CAMPAGNE.prise);assert(c.CAMPAGNE.clientsPresentes.includes('Boulangerie'));assert(!c.CAMPAGNE.clientsPresentes.includes('Laiterie'));const names=['Boulangerie','Scierie'];c.chargerCampagne({campagne:{mv:4,tv:4,xp:1000,mission:30,prise:false,clientsPresentes:names}});assert.deepEqual(Array.from(c.CAMPAGNE.clientsPresentes),names);assert(!c.CAMPAGNE.prise);});
test('Every deliverable product has an existing icon, with compact PNG assets for sea and wood',()=>{const c=setup();for(const [k,p] of Object.entries(c.PRODUITS)){if(p.interne)continue;assert(c.VIGNETTES[k],k);assert(fs.existsSync(path.join(__dirname,'../../produits',c.VIGNETTES[k]+'.png')),k);}for(const k of ['poisson','crustaces','grumes']){const b=fs.readFileSync(path.join(__dirname,'../../produits',k+'.png'));assert.equal(b.readUInt32BE(16),78);assert.equal(b.readUInt32BE(20),78);assert(b.length<6000);assert(b.includes(Buffer.from('tRNS')));}});
test('The renamed fishing-boat shop preserves its introduction in older saves',()=>{const c=setup();c.chargerCampagne({campagne:{mv:4,tv:4,xp:10000,mission:33,prise:false,clientsPresentes:['Chantier naval','Scierie']}});assert.deepEqual(Array.from(c.CAMPAGNE.clientsPresentes),['Comptoir des pêcheurs','Scierie']);assert.equal(c.CAMPAGNE.mission,33);assert.equal(c.CAMPAGNE.prise,false);});
console.log(count+' progression and transport tests passed.');
